// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Fortios
{
    public static class GetSystemAliaslist
    {
        /// <summary>
        /// Provides a list of `fortios.SystemAlias`.
        /// </summary>
        public static Task<GetSystemAliaslistResult> InvokeAsync(GetSystemAliaslistArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSystemAliaslistResult>("fortios:index/getSystemAliaslist:getSystemAliaslist", args ?? new GetSystemAliaslistArgs(), options.WithDefaults());

        /// <summary>
        /// Provides a list of `fortios.SystemAlias`.
        /// </summary>
        public static Output<GetSystemAliaslistResult> Invoke(GetSystemAliaslistInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSystemAliaslistResult>("fortios:index/getSystemAliaslist:getSystemAliaslist", args ?? new GetSystemAliaslistInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSystemAliaslistArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// A filter used to scope the list. See Filter results of datasource.
        /// </summary>
        [Input("filter")]
        public string? Filter { get; set; }

        /// <summary>
        /// Specifies the vdom to which the data source will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
        /// </summary>
        [Input("vdomparam")]
        public string? Vdomparam { get; set; }

        public GetSystemAliaslistArgs()
        {
        }
        public static new GetSystemAliaslistArgs Empty => new GetSystemAliaslistArgs();
    }

    public sealed class GetSystemAliaslistInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// A filter used to scope the list. See Filter results of datasource.
        /// </summary>
        [Input("filter")]
        public Input<string>? Filter { get; set; }

        /// <summary>
        /// Specifies the vdom to which the data source will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
        /// </summary>
        [Input("vdomparam")]
        public Input<string>? Vdomparam { get; set; }

        public GetSystemAliaslistInvokeArgs()
        {
        }
        public static new GetSystemAliaslistInvokeArgs Empty => new GetSystemAliaslistInvokeArgs();
    }


    [OutputType]
    public sealed class GetSystemAliaslistResult
    {
        public readonly string? Filter;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// A list of the `fortios.SystemAlias`.
        /// </summary>
        public readonly ImmutableArray<string> Namelists;
        public readonly string? Vdomparam;

        [OutputConstructor]
        private GetSystemAliaslistResult(
            string? filter,

            string id,

            ImmutableArray<string> namelists,

            string? vdomparam)
        {
            Filter = filter;
            Id = id;
            Namelists = namelists;
            Vdomparam = vdomparam;
        }
    }
}
