// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Fortios
{
    public static class GetSystemIpv6neighborcachelist
    {
        /// <summary>
        /// Provides a list of `fortios.SystemIpv6neighborcache`.
        /// </summary>
        public static Task<GetSystemIpv6neighborcachelistResult> InvokeAsync(GetSystemIpv6neighborcachelistArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSystemIpv6neighborcachelistResult>("fortios:index/getSystemIpv6neighborcachelist:getSystemIpv6neighborcachelist", args ?? new GetSystemIpv6neighborcachelistArgs(), options.WithDefaults());

        /// <summary>
        /// Provides a list of `fortios.SystemIpv6neighborcache`.
        /// </summary>
        public static Output<GetSystemIpv6neighborcachelistResult> Invoke(GetSystemIpv6neighborcachelistInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSystemIpv6neighborcachelistResult>("fortios:index/getSystemIpv6neighborcachelist:getSystemIpv6neighborcachelist", args ?? new GetSystemIpv6neighborcachelistInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSystemIpv6neighborcachelistArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// A filter used to scope the list. See Filter results of datasource.
        /// </summary>
        [Input("filter")]
        public string? Filter { get; set; }

        /// <summary>
        /// Specifies the vdom to which the data source will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
        /// </summary>
        [Input("vdomparam")]
        public string? Vdomparam { get; set; }

        public GetSystemIpv6neighborcachelistArgs()
        {
        }
        public static new GetSystemIpv6neighborcachelistArgs Empty => new GetSystemIpv6neighborcachelistArgs();
    }

    public sealed class GetSystemIpv6neighborcachelistInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// A filter used to scope the list. See Filter results of datasource.
        /// </summary>
        [Input("filter")]
        public Input<string>? Filter { get; set; }

        /// <summary>
        /// Specifies the vdom to which the data source will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
        /// </summary>
        [Input("vdomparam")]
        public Input<string>? Vdomparam { get; set; }

        public GetSystemIpv6neighborcachelistInvokeArgs()
        {
        }
        public static new GetSystemIpv6neighborcachelistInvokeArgs Empty => new GetSystemIpv6neighborcachelistInvokeArgs();
    }


    [OutputType]
    public sealed class GetSystemIpv6neighborcachelistResult
    {
        public readonly string? Filter;
        /// <summary>
        /// A list of the `fortios.SystemIpv6neighborcache`.
        /// </summary>
        public readonly ImmutableArray<int> Fosidlists;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string? Vdomparam;

        [OutputConstructor]
        private GetSystemIpv6neighborcachelistResult(
            string? filter,

            ImmutableArray<int> fosidlists,

            string id,

            string? vdomparam)
        {
            Filter = filter;
            Fosidlists = fosidlists;
            Id = id;
            Vdomparam = vdomparam;
        }
    }
}
