// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Fortios
{
    /// <summary>
    /// Configure FortiSwitch spanning tree protocol (STP).
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Fortios = Pulumiverse.Fortios;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var trname = new Fortios.SwitchcontrollerStpsettings("trname", new()
    ///     {
    ///         ForwardTime = 15,
    ///         HelloTime = 2,
    ///         MaxAge = 20,
    ///         MaxHops = 20,
    ///         PendingTimer = 4,
    ///         Revision = 0,
    ///         Status = "enable",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// SwitchController StpSettings can be imported using any of these accepted formats
    /// 
    /// ```sh
    ///  $ pulumi import fortios:index/switchcontrollerStpsettings:SwitchcontrollerStpsettings labelname SwitchControllerStpSettings
    /// ```
    /// 
    ///  If you do not want to import arguments of block$ export "FORTIOS_IMPORT_TABLE"="false"
    /// 
    /// ```sh
    ///  $ pulumi import fortios:index/switchcontrollerStpsettings:SwitchcontrollerStpsettings labelname SwitchControllerStpSettings
    /// ```
    /// 
    ///  $ unset "FORTIOS_IMPORT_TABLE"
    /// </summary>
    [FortiosResourceType("fortios:index/switchcontrollerStpsettings:SwitchcontrollerStpsettings")]
    public partial class SwitchcontrollerStpsettings : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Period of time a port is in listening and learning state (4 - 30 sec, default = 15).
        /// </summary>
        [Output("forwardTime")]
        public Output<int> ForwardTime { get; private set; } = null!;

        /// <summary>
        /// Period of time between successive STP frame Bridge Protocol Data Units (BPDUs) sent on a port (1 - 10 sec, default = 2).
        /// </summary>
        [Output("helloTime")]
        public Output<int> HelloTime { get; private set; } = null!;

        /// <summary>
        /// Maximum time before a bridge port saves its configuration BPDU information (6 - 40 sec, default = 20).
        /// </summary>
        [Output("maxAge")]
        public Output<int> MaxAge { get; private set; } = null!;

        /// <summary>
        /// Maximum number of hops between the root bridge and the furthest bridge (1- 40, default = 20).
        /// </summary>
        [Output("maxHops")]
        public Output<int> MaxHops { get; private set; } = null!;

        /// <summary>
        /// Name of global STP settings configuration.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Pending time (1 - 15 sec, default = 4).
        /// </summary>
        [Output("pendingTimer")]
        public Output<int> PendingTimer { get; private set; } = null!;

        /// <summary>
        /// STP revision number (0 - 65535).
        /// </summary>
        [Output("revision")]
        public Output<int> Revision { get; private set; } = null!;

        /// <summary>
        /// Enable/disable STP. Valid values: `enable`, `disable`.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
        /// </summary>
        [Output("vdomparam")]
        public Output<string?> Vdomparam { get; private set; } = null!;


        /// <summary>
        /// Create a SwitchcontrollerStpsettings resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SwitchcontrollerStpsettings(string name, SwitchcontrollerStpsettingsArgs? args = null, CustomResourceOptions? options = null)
            : base("fortios:index/switchcontrollerStpsettings:SwitchcontrollerStpsettings", name, args ?? new SwitchcontrollerStpsettingsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SwitchcontrollerStpsettings(string name, Input<string> id, SwitchcontrollerStpsettingsState? state = null, CustomResourceOptions? options = null)
            : base("fortios:index/switchcontrollerStpsettings:SwitchcontrollerStpsettings", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse/pulumi-fortios",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SwitchcontrollerStpsettings resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SwitchcontrollerStpsettings Get(string name, Input<string> id, SwitchcontrollerStpsettingsState? state = null, CustomResourceOptions? options = null)
        {
            return new SwitchcontrollerStpsettings(name, id, state, options);
        }
    }

    public sealed class SwitchcontrollerStpsettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Period of time a port is in listening and learning state (4 - 30 sec, default = 15).
        /// </summary>
        [Input("forwardTime")]
        public Input<int>? ForwardTime { get; set; }

        /// <summary>
        /// Period of time between successive STP frame Bridge Protocol Data Units (BPDUs) sent on a port (1 - 10 sec, default = 2).
        /// </summary>
        [Input("helloTime")]
        public Input<int>? HelloTime { get; set; }

        /// <summary>
        /// Maximum time before a bridge port saves its configuration BPDU information (6 - 40 sec, default = 20).
        /// </summary>
        [Input("maxAge")]
        public Input<int>? MaxAge { get; set; }

        /// <summary>
        /// Maximum number of hops between the root bridge and the furthest bridge (1- 40, default = 20).
        /// </summary>
        [Input("maxHops")]
        public Input<int>? MaxHops { get; set; }

        /// <summary>
        /// Name of global STP settings configuration.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Pending time (1 - 15 sec, default = 4).
        /// </summary>
        [Input("pendingTimer")]
        public Input<int>? PendingTimer { get; set; }

        /// <summary>
        /// STP revision number (0 - 65535).
        /// </summary>
        [Input("revision")]
        public Input<int>? Revision { get; set; }

        /// <summary>
        /// Enable/disable STP. Valid values: `enable`, `disable`.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
        /// </summary>
        [Input("vdomparam")]
        public Input<string>? Vdomparam { get; set; }

        public SwitchcontrollerStpsettingsArgs()
        {
        }
        public static new SwitchcontrollerStpsettingsArgs Empty => new SwitchcontrollerStpsettingsArgs();
    }

    public sealed class SwitchcontrollerStpsettingsState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Period of time a port is in listening and learning state (4 - 30 sec, default = 15).
        /// </summary>
        [Input("forwardTime")]
        public Input<int>? ForwardTime { get; set; }

        /// <summary>
        /// Period of time between successive STP frame Bridge Protocol Data Units (BPDUs) sent on a port (1 - 10 sec, default = 2).
        /// </summary>
        [Input("helloTime")]
        public Input<int>? HelloTime { get; set; }

        /// <summary>
        /// Maximum time before a bridge port saves its configuration BPDU information (6 - 40 sec, default = 20).
        /// </summary>
        [Input("maxAge")]
        public Input<int>? MaxAge { get; set; }

        /// <summary>
        /// Maximum number of hops between the root bridge and the furthest bridge (1- 40, default = 20).
        /// </summary>
        [Input("maxHops")]
        public Input<int>? MaxHops { get; set; }

        /// <summary>
        /// Name of global STP settings configuration.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Pending time (1 - 15 sec, default = 4).
        /// </summary>
        [Input("pendingTimer")]
        public Input<int>? PendingTimer { get; set; }

        /// <summary>
        /// STP revision number (0 - 65535).
        /// </summary>
        [Input("revision")]
        public Input<int>? Revision { get; set; }

        /// <summary>
        /// Enable/disable STP. Valid values: `enable`, `disable`.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
        /// </summary>
        [Input("vdomparam")]
        public Input<string>? Vdomparam { get; set; }

        public SwitchcontrollerStpsettingsState()
        {
        }
        public static new SwitchcontrollerStpsettingsState Empty => new SwitchcontrollerStpsettingsState();
    }
}
