// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fortios

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides a list of `FirewallPolicy6`.
func GetFirewallPolicy6list(ctx *pulumi.Context, args *GetFirewallPolicy6listArgs, opts ...pulumi.InvokeOption) (*GetFirewallPolicy6listResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetFirewallPolicy6listResult
	err := ctx.Invoke("fortios:index/getFirewallPolicy6list:getFirewallPolicy6list", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFirewallPolicy6list.
type GetFirewallPolicy6listArgs struct {
	// A filter used to scope the list. See Filter results of datasource.
	Filter *string `pulumi:"filter"`
	// Specifies the vdom to which the data source will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam *string `pulumi:"vdomparam"`
}

// A collection of values returned by getFirewallPolicy6list.
type GetFirewallPolicy6listResult struct {
	Filter *string `pulumi:"filter"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// A list of the `FirewallPolicy6`.
	Policyidlists []int   `pulumi:"policyidlists"`
	Vdomparam     *string `pulumi:"vdomparam"`
}

func GetFirewallPolicy6listOutput(ctx *pulumi.Context, args GetFirewallPolicy6listOutputArgs, opts ...pulumi.InvokeOption) GetFirewallPolicy6listResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetFirewallPolicy6listResult, error) {
			args := v.(GetFirewallPolicy6listArgs)
			r, err := GetFirewallPolicy6list(ctx, &args, opts...)
			var s GetFirewallPolicy6listResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetFirewallPolicy6listResultOutput)
}

// A collection of arguments for invoking getFirewallPolicy6list.
type GetFirewallPolicy6listOutputArgs struct {
	// A filter used to scope the list. See Filter results of datasource.
	Filter pulumi.StringPtrInput `pulumi:"filter"`
	// Specifies the vdom to which the data source will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrInput `pulumi:"vdomparam"`
}

func (GetFirewallPolicy6listOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFirewallPolicy6listArgs)(nil)).Elem()
}

// A collection of values returned by getFirewallPolicy6list.
type GetFirewallPolicy6listResultOutput struct{ *pulumi.OutputState }

func (GetFirewallPolicy6listResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFirewallPolicy6listResult)(nil)).Elem()
}

func (o GetFirewallPolicy6listResultOutput) ToGetFirewallPolicy6listResultOutput() GetFirewallPolicy6listResultOutput {
	return o
}

func (o GetFirewallPolicy6listResultOutput) ToGetFirewallPolicy6listResultOutputWithContext(ctx context.Context) GetFirewallPolicy6listResultOutput {
	return o
}

func (o GetFirewallPolicy6listResultOutput) Filter() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetFirewallPolicy6listResult) *string { return v.Filter }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetFirewallPolicy6listResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetFirewallPolicy6listResult) string { return v.Id }).(pulumi.StringOutput)
}

// A list of the `FirewallPolicy6`.
func (o GetFirewallPolicy6listResultOutput) Policyidlists() pulumi.IntArrayOutput {
	return o.ApplyT(func(v GetFirewallPolicy6listResult) []int { return v.Policyidlists }).(pulumi.IntArrayOutput)
}

func (o GetFirewallPolicy6listResultOutput) Vdomparam() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetFirewallPolicy6listResult) *string { return v.Vdomparam }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetFirewallPolicy6listResultOutput{})
}
