// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Fortios.Router.Outputs
{

    [OutputType]
    public sealed class IsisSummaryAddress6
    {
        /// <summary>
        /// isis-net ID.
        /// </summary>
        public readonly int? Id;
        /// <summary>
        /// Level. Valid values: `level-1-2`, `level-1`, `level-2`.
        /// 
        /// The `summary_address6` block supports:
        /// </summary>
        public readonly string? Level;
        /// <summary>
        /// IPv6 prefix.
        /// </summary>
        public readonly string? Prefix6;

        [OutputConstructor]
        private IsisSummaryAddress6(
            int? id,

            string? level,

            string? prefix6)
        {
            Id = id;
            Level = level;
            Prefix6 = prefix6;
        }
    }
}
