// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sys

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides a list of `sys.Wccp`.
func GetWccplist(ctx *pulumi.Context, args *GetWccplistArgs, opts ...pulumi.InvokeOption) (*GetWccplistResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetWccplistResult
	err := ctx.Invoke("fortios:sys/getWccplist:getWccplist", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getWccplist.
type GetWccplistArgs struct {
	// A filter used to scope the list. See Filter results of datasource.
	Filter *string `pulumi:"filter"`
	// Specifies the vdom to which the data source will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam *string `pulumi:"vdomparam"`
}

// A collection of values returned by getWccplist.
type GetWccplistResult struct {
	Filter *string `pulumi:"filter"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// A list of the `sys.Wccp`.
	ServiceIdlists []string `pulumi:"serviceIdlists"`
	Vdomparam      *string  `pulumi:"vdomparam"`
}

func GetWccplistOutput(ctx *pulumi.Context, args GetWccplistOutputArgs, opts ...pulumi.InvokeOption) GetWccplistResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetWccplistResult, error) {
			args := v.(GetWccplistArgs)
			r, err := GetWccplist(ctx, &args, opts...)
			var s GetWccplistResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetWccplistResultOutput)
}

// A collection of arguments for invoking getWccplist.
type GetWccplistOutputArgs struct {
	// A filter used to scope the list. See Filter results of datasource.
	Filter pulumi.StringPtrInput `pulumi:"filter"`
	// Specifies the vdom to which the data source will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
	Vdomparam pulumi.StringPtrInput `pulumi:"vdomparam"`
}

func (GetWccplistOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetWccplistArgs)(nil)).Elem()
}

// A collection of values returned by getWccplist.
type GetWccplistResultOutput struct{ *pulumi.OutputState }

func (GetWccplistResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetWccplistResult)(nil)).Elem()
}

func (o GetWccplistResultOutput) ToGetWccplistResultOutput() GetWccplistResultOutput {
	return o
}

func (o GetWccplistResultOutput) ToGetWccplistResultOutputWithContext(ctx context.Context) GetWccplistResultOutput {
	return o
}

func (o GetWccplistResultOutput) Filter() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetWccplistResult) *string { return v.Filter }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetWccplistResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetWccplistResult) string { return v.Id }).(pulumi.StringOutput)
}

// A list of the `sys.Wccp`.
func (o GetWccplistResultOutput) ServiceIdlists() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetWccplistResult) []string { return v.ServiceIdlists }).(pulumi.StringArrayOutput)
}

func (o GetWccplistResultOutput) Vdomparam() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetWccplistResult) *string { return v.Vdomparam }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetWccplistResultOutput{})
}
