// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Fortios.Waf.Inputs
{

    public sealed class ProfileAddressListGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("blockedAddresses")]
        private InputList<Inputs.ProfileAddressListBlockedAddressGetArgs>? _blockedAddresses;

        /// <summary>
        /// Blocked address. The structure of `blocked_address` block is documented below.
        /// </summary>
        public InputList<Inputs.ProfileAddressListBlockedAddressGetArgs> BlockedAddresses
        {
            get => _blockedAddresses ?? (_blockedAddresses = new InputList<Inputs.ProfileAddressListBlockedAddressGetArgs>());
            set => _blockedAddresses = value;
        }

        /// <summary>
        /// Enable/disable logging on blocked addresses. Valid values: `enable`, `disable`.
        /// </summary>
        [Input("blockedLog")]
        public Input<string>? BlockedLog { get; set; }

        /// <summary>
        /// Severity. Valid values: `high`, `medium`, `low`.
        /// </summary>
        [Input("severity")]
        public Input<string>? Severity { get; set; }

        /// <summary>
        /// Status. Valid values: `enable`, `disable`.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("trustedAddresses")]
        private InputList<Inputs.ProfileAddressListTrustedAddressGetArgs>? _trustedAddresses;

        /// <summary>
        /// Trusted address. The structure of `trusted_address` block is documented below.
        /// </summary>
        public InputList<Inputs.ProfileAddressListTrustedAddressGetArgs> TrustedAddresses
        {
            get => _trustedAddresses ?? (_trustedAddresses = new InputList<Inputs.ProfileAddressListTrustedAddressGetArgs>());
            set => _trustedAddresses = value;
        }

        public ProfileAddressListGetArgs()
        {
        }
        public static new ProfileAddressListGetArgs Empty => new ProfileAddressListGetArgs();
    }
}
