// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Configure FIPS-CC mode.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as fortios from "@pulumiverse/fortios";
 *
 * const trname = new fortios.SystemFipscc("trname", {
 *     entropyToken: "enable",
 *     keyGenerationSelfTest: "disable",
 *     selfTestPeriod: 1440,
 *     status: "disable",
 * });
 * ```
 *
 * ## Import
 *
 * System FipsCc can be imported using any of these accepted formats
 *
 * ```sh
 *  $ pulumi import fortios:index/systemFipscc:SystemFipscc labelname SystemFipsCc
 * ```
 *
 *  If you do not want to import arguments of block$ export "FORTIOS_IMPORT_TABLE"="false"
 *
 * ```sh
 *  $ pulumi import fortios:index/systemFipscc:SystemFipscc labelname SystemFipsCc
 * ```
 *
 *  $ unset "FORTIOS_IMPORT_TABLE"
 */
export class SystemFipscc extends pulumi.CustomResource {
    /**
     * Get an existing SystemFipscc resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SystemFipsccState, opts?: pulumi.CustomResourceOptions): SystemFipscc {
        return new SystemFipscc(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'fortios:index/systemFipscc:SystemFipscc';

    /**
     * Returns true if the given object is an instance of SystemFipscc.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SystemFipscc {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SystemFipscc.__pulumiType;
    }

    /**
     * Enable/disable/dynamic entropy token. Valid values: `enable`, `disable`, `dynamic`.
     */
    public readonly entropyToken!: pulumi.Output<string>;
    /**
     * Enable/disable self tests after key generation. Valid values: `enable`, `disable`.
     */
    public readonly keyGenerationSelfTest!: pulumi.Output<string>;
    /**
     * Self test period.
     */
    public readonly selfTestPeriod!: pulumi.Output<number>;
    /**
     * Enable/disable FIPS-CC mode. Valid values: `enable`, `disable`.
     */
    public readonly status!: pulumi.Output<string>;
    /**
     * Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
     */
    public readonly vdomparam!: pulumi.Output<string | undefined>;

    /**
     * Create a SystemFipscc resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SystemFipsccArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SystemFipsccArgs | SystemFipsccState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SystemFipsccState | undefined;
            resourceInputs["entropyToken"] = state ? state.entropyToken : undefined;
            resourceInputs["keyGenerationSelfTest"] = state ? state.keyGenerationSelfTest : undefined;
            resourceInputs["selfTestPeriod"] = state ? state.selfTestPeriod : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["vdomparam"] = state ? state.vdomparam : undefined;
        } else {
            const args = argsOrState as SystemFipsccArgs | undefined;
            resourceInputs["entropyToken"] = args ? args.entropyToken : undefined;
            resourceInputs["keyGenerationSelfTest"] = args ? args.keyGenerationSelfTest : undefined;
            resourceInputs["selfTestPeriod"] = args ? args.selfTestPeriod : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
            resourceInputs["vdomparam"] = args ? args.vdomparam : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SystemFipscc.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SystemFipscc resources.
 */
export interface SystemFipsccState {
    /**
     * Enable/disable/dynamic entropy token. Valid values: `enable`, `disable`, `dynamic`.
     */
    entropyToken?: pulumi.Input<string>;
    /**
     * Enable/disable self tests after key generation. Valid values: `enable`, `disable`.
     */
    keyGenerationSelfTest?: pulumi.Input<string>;
    /**
     * Self test period.
     */
    selfTestPeriod?: pulumi.Input<number>;
    /**
     * Enable/disable FIPS-CC mode. Valid values: `enable`, `disable`.
     */
    status?: pulumi.Input<string>;
    /**
     * Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
     */
    vdomparam?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SystemFipscc resource.
 */
export interface SystemFipsccArgs {
    /**
     * Enable/disable/dynamic entropy token. Valid values: `enable`, `disable`, `dynamic`.
     */
    entropyToken?: pulumi.Input<string>;
    /**
     * Enable/disable self tests after key generation. Valid values: `enable`, `disable`.
     */
    keyGenerationSelfTest?: pulumi.Input<string>;
    /**
     * Self test period.
     */
    selfTestPeriod?: pulumi.Input<number>;
    /**
     * Enable/disable FIPS-CC mode. Valid values: `enable`, `disable`.
     */
    status?: pulumi.Input<string>;
    /**
     * Specifies the vdom to which the resource will be applied when the FortiGate unit is running in VDOM mode. Only one vdom can be specified. If you want to inherit the vdom configuration of the provider, please do not set this parameter.
     */
    vdomparam?: pulumi.Input<string>;
}
